version: '3.8'
services:
  api:
    container_name: pepo-fut-api
    image: pepo-fut-api
    ports:
      - '8081:3333'
    depends_on:
      - db
  db:
    container_name: pepo-fut-db
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pepo_fut
    ports:
      - '5432:5432'
